#!/bin/sh /etc/rc.common
# Copyright (C) 2012 OpenWrt.org

# needs to start before the atm layer which starts at 50
START=48
USE_PROCD=1

EXTRA_COMMANDS="status lucistat"
EXTRA_HELP="	status  Get DSL status information
	lucistat  Get status information if lua friendly format"

[ -f /lib/functions/lantiq_dsl.sh ] && . /lib/functions/lantiq_dsl.sh


lowlevel_cfg() {
	echo "# VRX Low Level Configuration File
#
# Parameters must be separated by tabs or spaces.
# Empty lines and comments will be ignored.
#

# nFilter
#
# NA     = -1
# OFF    = 0
# ISDN   = 1
# POTS   = 2
# POTS_2 = 3
# POTS_3 = 4
#
#  (dec)
    -1

# nHsToneGroupMode nHsToneGroup_A       nHsToneGroup_V    nHsToneGroup_AV
#
# NA     = -1      NA         = -1      see               see
# AUTO   = 0       VDSL2_B43  = 0x0001  nHsToneGroup_A    nHsToneGroup_A
# MANUAL = 1       VDSL2_A43  = 0x0002
#                  VDSL2_V43  = 0x0004
#                  VDSL1_V43P = 0x0008
#                  VDSL1_V43I = 0x0010
#                  ADSL1_C43  = 0x0020
#                  ADSL2_J43  = 0x0040
#                  ADSL2_B43C = 0x0080
#                  ADSL2_A43C = 0x0100
#
#  (dec)           (hex)                (hex)             (hex)
     $1             $2			$3		 0x0

#   nBaseAddr     nIrqNum
#
#     (hex)        (dec)
    0x1e116000      63

# nUtopiaPhyAdr   nUtopiaBusWidth      nPosPhyParity
#                 default(16b) = 0     NA   = -1
#                 8-bit        = 1     ODD  = 0
#                 16-bit       = 2
#
#
#    (hex)            (dec)                (dec)
      0xFF              0                    0

# bNtrEnable
#
#  (dec)
    0" > /tmp/lowlevel.cfg
}

service_triggers() {
	procd_add_reload_trigger network
}

start_service() {
	local annex
	local firmware
	local tone_adsl
	local tone_vdsl
	local xtse
	local lowlevel
	local mode
	local mode_num

	config_load network
	config_get annex dsl annex
	config_get mode dsl mode
	config_get firmware dsl firmware
	config_get xfer_mode dsl xfer_mode
	config_get xtse dsl xtse
	config_get tone_adsl dsl tone_adsl
	config_get tone_vdsl dsl tone_vdsl

	case "${mode}" in
	vdsl)
		[ -z "${xfer_mode}" ] && xfer_mode=ptm
		mode_num=2
		case "${annex}" in
		a)
			[ -z "${xtse}" ] && xtse="05_00_04_00_4C_01_04_07"
			;;
		b)
			[ -z "${xtse}" ] && xtse="10_00_10_00_00_04_01_07"
			;;
		*)
			;;
		esac
		;;
	adsl)
		[ -z "${xfer_mode}" ] && xfer_mode=atm
		mode_num=1

		case "${annex}" in
		a)
			[ -z "${xtse}" ] && xtse="05_00_04_00_4C_01_04_00"
			;;
		b)
			[ -z "${xtse}" ] && xtse="10_00_10_00_00_04_01_00"
			;;
		*)
			;;
		esac
		;;
	*)
		echo "mode not set to vdsl or adsl"
		return 1
		;;
	esac

	case "${xfer_mode}" in
	atm)
		LOAD=ltq_atm_vr9
		UNLOAD=ltq_ptm_vr9
		;;
	ptm)
		LOAD=ltq_ptm_vr9
		UNLOAD=ltq_atm_vr9
		;;
	*)
		echo "xfer_mode not set to atm or ptm"
		return 1
		;;
	esac

	if [ -z "${firmware}" ]; then
		if grep -qE "system type.*: (VR9|xRX200)" /proc/cpuinfo; then
			case "${annex}" in
			a)
				if [ -f "/lib/firmware/lantiq-vrx200-a.bin" ]; then
					firmware=/lib/firmware/lantiq-vrx200-a.bin
				elif [ -f "/tmp/lantiq-vrx200-a.bin" ]; then
					firmware=/tmp/lantiq-vrx200-a.bin
				elif [ -f "/lib/firmware/lantiq-vrx200-b.bin" ] && [ -f "/lib/firmware/lantiq-vrx200-b-to-a.bspatch" ]; then
					bspatch /lib/firmware/lantiq-vrx200-b.bin \
						/tmp/lantiq-vrx200-a.bin \
						/lib/firmware/lantiq-vrx200-b-to-a.bspatch
					firmware=/tmp/lantiq-vrx200-a.bin
				else
					echo "firmware for annex a not found"
					return 1
				fi
				;;
			b)
				if [ -f "/lib/firmware/lantiq-vrx200-b.bin" ]; then
					firmware=/lib/firmware/lantiq-vrx200-b.bin
				elif [ -f "/tmp/lantiq-vrx200-b.bin" ]; then
					firmware=/tmp/lantiq-vrx200-b.bin
				elif [ -f "/lib/firmware/lantiq-vrx200-a.bin" ] && [ -f "/lib/firmware/lantiq-vrx200-a-to-b.bspatch" ]; then
					bspatch /lib/firmware/lantiq-vrx200-a.bin \
						/tmp/lantiq-vrx200-b.bin \
						/lib/firmware/lantiq-vrx200-a-to-b.bspatch
					firmware=/tmp/lantiq-vrx200-b.bin
				else
					echo "firmware for annex b not found"
					return 1
				fi
				;;
			*)
				echo "annex type not supported use a or b"
				return 1
				;;
			esac
		fi
	fi
	[ -f "${firmware}" ] || {
		echo "failed to find firmware: $firmware"
		return 1
	}

	[ -n "${tone_adsl}" ] && [ -n "${tone_vdsl}" ] && {
		lowlevel_cfg "1" "${tone_adsl}" "${tone_vdsl}"
		lowlevel="-l /tmp/lowlevel.cfg"
	}

	procd_open_instance
	procd_set_param command /sbin/vdsl_cpe_control_wrapper \
			-i$xtse \
			-n /sbin/dsl_notify.sh \
			-f ${firmware} \
			$lowlevel \
			-M ${mode_num}
	procd_append_param env "LOAD=$LOAD" "UNLOAD=$UNLOAD"
	procd_close_instance
}

stop_service() {
	dsl_cmd quit
	DSL_NOTIFICATION_TYPE="DSL_INTERFACE_STATUS" \
	DSL_INTERFACE_STATUS="DOWN" \
		/sbin/dsl_notify.sh
}
