name: Build all core packages

on:
  pull_request:
    paths:
      - '.github/workflows/packages.yml'
      - 'config/**'
      - 'include/**'
      - 'package/**'
      - 'target/linux/generic/**'
      - 'toolchain/**'
  push:
    paths:
      - '.github/workflows/packages.yml'
      - 'config/**'
      - 'include/**'
      - 'package/**'
      - 'target/linux/generic/**'
      - 'toolchain/**'

permissions:
  contents: read

jobs:
  build:
    name: Build all core packages
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        include:
          - name: malta-be
            target: malta
            subtarget: be
          - name: x86-64
            target: x86
            subtarget: 64

    permissions:
      contents: read
      packages: read

    uses: ./.github/workflows/target-build.yaml
    with:
      target: ${{ matrix.target }}
      subtarget: ${{ matrix.subtarget }}
      build_all_kmods: true
      build_all_modules: true
      build_full: true
