name: Build lantiq target

on:
  pull_request:
    paths:
      - '.github/workflows/target-lantiq.yaml'
      - 'target/linux/lantiq/**'
      - 'package/kernel/lantiq/**'
      - 'package/boot/uboot-lantiq/**'
  push:
    paths:
      - '.github/workflows/target-lantiq.yaml'
      - 'target/linux/lantiq/**'
      - 'package/kernel/lantiq/**'
      - 'package/boot/uboot-lantiq/**'

jobs:
  build_target:
    strategy:
      fail-fast: False
      matrix:
        subtarget: [ase, xrx200, xway, xway_legacy]
        testing: [false, true]
    uses: ./.github/workflows/target-build.yaml
    with:
      target: "lantiq/${{ matrix.subtarget }}"
      testing: ${{ matrix.testing }}


  check_kernel:
    strategy:
      fail-fast: False
      matrix:
        subtarget: [ase]
        testing: [false, true]
    uses: ./.github/workflows/target-check-patch.yaml
    with:
      target: "lantiq/${{ matrix.subtarget }}"
      testing: ${{ matrix.testing }}
